# Dependencies
highlighter: true

# Permalinks
permalink:        pretty


# Setup
title:            Abdullah Bin Salm
tagline:          An awsome developer
url:              http://abinsalm.github.io
baseurl:          /

author:
  name:           Abdullah Bin Salm
  url:            http://abinsalm.github.io
  email:          dragon_z_m10dx@hotmail.com

paginate:         1

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/abinsalm/abinsalm.github.io

# Plugins
highlighter:      pygments

# This is the list of pages to incldue in the header of the website.
pages_list: {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}